spring:
  application:
    name: blogtest
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: eom
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  sql:
    init:
      mode: always
      encoding: UTF-8
jwt:
  issuer: dja3065@naver.com
  secret_key: study-springboot